apiVersion: v1
name: statefulset
version: 1.0.0
description: The Universal Statefulset Helm Chart
keywords:
  - statefulset
  - helm
home: https://github.com/JacksonFraser/Universal-Kubernetes-Helm-Charts
sources:
  - https://github.com/JacksonFraser/Universal-Kubernetes-Helm-Charts/charts/statefulset
