{{- if or (eq .Values.serviceAccount.enabled true) (eq .Values.rbac.create true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}
  {{- include "labels" . | indent 2 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
