################################################
# Standardized Templates - Argo Cronjob
# Author/Maintainer: Farley <farley@neonsurge.com>
# TODO: This needs to be tested and re-aligned to deployment/statefulset standards
################################################
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ template "name" . }}
{{- include "labels" . | indent 2 }}
spec:
  schedule: {{ required "Please specify cronjob schedule, eg 0 0 * * * for once-per-day." .Values.schedule | quote }}
  concurrencyPolicy: {{ default "Forbid" .Values.concurrencyPolicy | quote }}
  successfulJobsHistoryLimit: {{ default 1 .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 3 .Values.failedJobsHistoryLimit }}
  startingDeadlineSeconds: {{ default 600 .Values.startingDeadlineSeconds }}
  {{- if .Values.timezone }}
  timezone: {{ .Values.timezone }}
  {{- end }}
  workflowMetadata:
{{- include "labels" . | indent 4 }}
  workflowSpec:
    podMetadata:
{{- include "labels" . | indent 6 }}
    entrypoint: {{ template "name" . }}
{{- if .Values.serviceAccount.enabled }}
    serviceAccountName: {{ template "name" . }}
{{- end }}
    backoffLimit: {{ default 0 .Values.backoffLimit }}
    parallelism: {{ default 1 .Values.parallelism }}
    completions: {{ default 1 .Values.completions }}
{{- if .Values.volumes }}
    volumes:
{{- with .Values.volumes }}
{{ toYaml . | indent 6 }}
{{- end -}}
{{- end }}
    templates:
      - name: {{ template "name" . }}
{{- include "labels" . | indent 8 }}
        container:
          image: "{{ template "get-repository" . }}:{{ template "get-release-tag" . }}"

{{- if .Values.image.command }}
          command: {{- range .Values.image.command }}
            - {{ . | quote }}
          {{- end }}
{{- end }}

{{- if .Values.image.args }}
          args: {{- range .Values.image.args }}
            - {{ . | quote }}
          {{- end }}
{{- end }}

{{- if .Values.image.imagePullPolicy }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
{{- end }}

          env:
            # Default env variables we want all containers to have
            - name: "POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: "POD_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CONTAINER_CPU_REQUESTS_MILLICORES
              valueFrom:
                resourceFieldRef:
                  resource: requests.cpu
                  divisor: 1m
            - name: CONTAINER_CPU_LIMITS_MILLICORES
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: 1m
{{- if .Values.usingMemoryKibiBytesEnvs }}
            - name: CONTAINER_MEMORY_REQUESTS_KIBIBYTES
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
                  divisor: 1Ki
            - name: CONTAINER_MEMORY_LIMITS_KIBIBYTES
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Ki
{{- else }}
            - name: CONTAINER_MEMORY_REQUESTS_MEGABYTES
              valueFrom:
                resourceFieldRef:
                  resource: requests.memory
                  divisor: 1Mi
            - name: CONTAINER_MEMORY_LIMITS_MEGABYTES
              valueFrom:
                resourceFieldRef:
                  resource: limits.memory
                  divisor: 1Mi
{{- end }}

            # Global variables placed in a "global" values file for all environments
            {{- if .Values.globalEnvs }}
            # Insert globals here, special handling so we can "tpl" these values and use eg: namespace in them
            {{- range .Values.globalEnvs }}
            - name: {{ .name | quote }}
              {{- if .value }}
              value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
{{ .valueFrom | toYaml | indent 16 }}
              {{- end }}
            {{- end }}
            {{- end }}

            # Insert secondary globals here, special handling so we can "tpl" these values and use eg: namespace in them
            {{- if .Values.globalEnvsSecondary }}
            {{- range .Values.globalEnvsSecondary }}
            - name: {{ .name | quote }}
              {{- if .value }}
              value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
{{ .valueFrom | toYaml | indent 16 }}
              {{- end }}
            {{- end }}
            {{- end }}

            # Insert extra envs here, for sub-values files inserts, with special handling so we can "tpl" in them
            {{- if .Values.extraEnvs }}
            {{- range .Values.extraEnvs }}
            - name: {{ .name | quote }}
              {{- if .value }}
              value: {{ with .value }}{{ tpl . $ | quote }}{{- end }}
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
{{ .valueFrom | toYaml | indent 16 }}
              {{- end }}
            {{- end }}
            {{- end }}

# If we want to pull env variables from other confimgaps or secrets
          envFrom:
            {{- with .Values.envFrom }}
{{ toYaml . | indent 12 }}
            {{- end }}

# This defines our resource limits
          resources:
{{ toYaml .Values.resources | indent 12 }}

# Service Account creation
{{- if or (eq .Values.serviceAccount.enabled true) (eq .Values.rbac.create true) }}
          serviceAccountName: {{ template "name" . }}
{{- end }}

# Volume mounts
{{- if .Values.volumeMounts }}
          volumeMounts:
{{- with .Values.volumeMounts }}
{{ toYaml . | indent 12 }}
{{- end -}}
{{- end }}

# This is our image pull secret references, if we have image pull secrets
{{- with .Values.image.imagePullSecrets }}
    imagePullSecrets:
{{ toYaml . | indent 6 }}
{{- end }}
